import { Metadata } from 'next';
import SignUpForm from './signup-form';

export const metadata: Metadata = {
  title: 'Sign Up Page',
  description: 'Generated by create next app',
};

const SignUpPage = () => {
  return <SignUpForm />;
};

export default SignUpPage;
