import { ThemeProvider } from '@/components/theme-provider';
import '@styles/globals.css';
import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';

const manrope = Manrope({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    template: '%s | Bookmark Manager App',
    default: 'Login Page | Bookmark Manager App',
  },
  description: 'Generated by create next app',
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${manrope.className} antialiased min-h-screen bg-neutral-100 dark:bg-neutral-900`}>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
